name: Build and test

on:
  push:
    branches: [ "main", "devel" ]
  pull_request:
    branches: [ "main", "devel" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

    - name: Install system dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libgtk-3-dev gcc-mingw-w64-x86-64
        version: 1
    
    - name: Cache Cargo registry and target directory
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ./target
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml', 'Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
