name: Provide development builds

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Install system dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libgtk-3-dev gcc-mingw-w64-x86-64
        version: 1
    
    - name: Install rustup Windows target
      run: rustup target add x86_64-pc-windows-gnu
    
    - name: Checkout source code
      uses: actions/checkout@v3
    
    - name: Linux release build
      run: cargo build --release --verbose

    - name: Upload Linux release build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ocdscope-linux-x86_64
        path: target/release/ocdscope
    
    - name: Windows release build
      run: cargo build --release --target x86_64-pc-windows-gnu --verbose
    
    - name: Upload Windows release build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ocdscope-windows-x86_64.exe
        path: target/x86_64-pc-windows-gnu/release/ocdscope.exe
    
